- ownCloud.xcodeproj/project.pbxproj
- ownCloud/Client/ClientQueryViewController.swift
- ownCloud/Client/OCSortMethod.swift
- ownCloud/Client/SortBar.swift
- ownCloud/Client/SortMethod.swift
- ownCloud/Resources/Localizable.strings
- ownCloud/Tools/UIDevide+UIUserInterfaceIdiom.swift
This PR aims to add support in the file list screen to different sorting methods.
The way I'm coding this is:
- I've created an enum with the possible sorting options, in our case I've coded:
```Swift
case alphabeticallyAscendant
case alphabeticallyDescendant
case type
case size
```
Taking advantage of the Swift's enums, the `SortMethod` enum has a method called `comparator()` which return a `Comparator`. This allows us to simply call
```Swift 
SortMethod.alphabeticallyAscendant.comparator()
```
to get the comparator for each sort method option in the enum.
Inside this method, there is a switch that returns the correct `Comparator` for each case.
- Next, I'll create a custom view with three buttons:
- ~~**Create folder button**: like in the files app, this button in this pull request is …
> File list view sorting

- ownCloud/Settings/SecuritySettingsSection.swift
- ownCloudTests/Security/BiometricalTests.swift
Add negative test to biometrical unlock.
Possibility to add more tests in the integration of biometrical with app settings (needed interaction with simulator to support biometrical unlock).
> Add UI tests on biometrical lock

- ownCloud/Theming/UI/ThemeNavigationController.swift
This fixes a retain cycle in ThemeNavigationController that had large side effects like f.ex. `OCCore`s and `ClientQueryViewController`s never getting released and causing conflicts with new instances of `OCCore`.
> Fix retain cycle in ThemeNavigationController

- ownCloud/Viewer/WebViewDisplayViewController.swift
Now the `.apk` files are not opened by the web view previewer so no more white screen.
https://github.com/owncloud/ios-app/issues/150
> Ban APK files from the web view previewer.

- ownCloud/Client/ClientItemCell.swift
This PR introduces a new constraint to don't allow the thumbnail height go above cell height.
https://github.com/owncloud/ios-app/issues/140
> Fix for the thumbnail height in ClientItemCell

- ownCloud/UI Elements/ImageScrollView.swift
Fixes a crash when trying to set the frame to the image view and the image view is nil. Now the frame is only set if the image view is not nil.
https://github.com/owncloud/ios-app/issues/154
> Fix for imageScrollView center function.

- ownCloud.xcodeproj/project.pbxproj
- ownCloud/AppDelegate.swift
- ownCloud/Client/Actions/Action.swift
- ownCloud/Client/Actions/Actions+Extensions/CreateFolderAction.swift
- ownCloud/Client/Actions/Actions+Extensions/DeleteAction.swift
- ownCloud/Client/Actions/Actions+Extensions/DuplicateAction.swift
- ownCloud/Client/Actions/Actions+Extensions/MoveAction.swift
- ownCloud/Client/Actions/Actions+Extensions/OpenInAction.swift
- ownCloud/Client/Actions/Actions+Extensions/RenameAction.swift
- ownCloud/Client/Actions/ClientDirectoryPickerViewController.swift
- ownCloud/Client/Actions/MoreViewController.swift
- ownCloud/Client/Actions/NamingViewController.swift
- ownCloud/Client/ClientQueryViewController.swift
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/SDK Extensions/OCItem+Extension.swift
- ownCloud/UI Elements/DownloadFileProgressHUDViewController.swift
- ownCloud/Viewer/DisplayHostViewController.swift
- ownCloud/Viewer/DisplayViewController.swift
I coded a new action in the card view controller that is launched through the 3 dots in the file list to be able to open in a file in another app.
https://github.com/owncloud/ios-app/issues/130
With this PR you're able to open one item in another app
_____
BUGS & IMPROVEMENTS
> [feature/open_in] Open in another app (via UIDocumentInteractionController) 

- ownCloudTests/Login/CreateBookmarkTests.swift
Include three extra tests to cover Certificates issue. We had only one test to check if the view is correct when the issue of type "Certificate" happens.
New tests included:
- Clicking on Certificate, the Certificate info is displayed
- Approving the Certificate, credentials fields are displayed (basic auth)
- Cancelling the Certificate, credentials fields are not displayed (basic auth)
> [feature/extend_authentication_suite_certificate_uitests] Expand authentication UI test suite with more Certificate UI tests 

- .swiftlint.yml
SwiftLint rules are designed to correctness in app code. UI tests are not fitting such rules:
- Test names use to be longer than `func`names, so they describe the scope of the test
- Trailing whitespaces to distinguish different parts of each test.
App and tests also run on different targets.
For such reasons, excluding test folder will avoid unnecessary warnings.
> Exclude app ownCloudTests from lint rules

- ownCloud/Client/Actions/Actions+Extensions/OpenInAction.swift
- ownCloud/Resources/en.lproj/Localizable.strings
Fix for https://github.com/owncloud/ios-app/issues/179
https://github.com/owncloud/ios-app/issues/179
> Offline behaviour in Open In Action

- .swiftlint.yml
- ownCloud/Bookmarks/BookmarkViewController.swift
- ownCloud/Client/Actions/NamingViewController.swift
- ownCloud/Client/ClientItemCell.swift
- ownCloud/Client/ClientQueryViewController.swift
- ownCloud/Client/SortBar.swift
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/Server List/ServerListBookmarkCell.swift
- ownCloud/Server List/ServerListTableViewController.swift
- ownCloud/Theming/NSObject+ThemeApplication.swift
- ownCloud/Theming/UI/ThemeButton.swift
- ownCloud/UI Elements/StaticTableViewRow.swift
- ownCloud/Viewer/DisplayViewController.swift
Improves the Voice Over suggestions and adds support for dynamic font sizes.
https://github.com/owncloud/ios-app/issues/196
> Accessibility improvements

- ownCloud/Settings/SecuritySettingsSection.swift
There was a missing view controller title in "Settings" > "Lock application"
#294 
- open Settings
- open "Lock application"
- view controller title should be visible
> #294 added missing view controller title for "Lock application"

- .tx/config
Removed the mapping of the Spanish language because was wrong and it is not necessary. "es" from TX is "es" also on the xcode project.
Include all the finished translations on the first release of ownCloud iOS App
After be merge Drone should update the file automatically
> Removed the es lang because was wrong and it is not necessary to map it

- ownCloud/Server List/ServerListTableViewController.xib
- ownCloud/Settings/Passcode/PasscodeViewController.swift
- ownCloud/Settings/Passcode/PasscodeViewController.xib
- changed full width button to a rounded button
- fixed passcode view, error label and cancel button for smaller display sizes (iPhone SE)
#302 
- remove full width buttons, because it doesn't look like a button (see #232)
- open settings
- enable / disable pass-lock 
- please test on iPhone SE, iPhone XS Max, iPad Pro 12,9
> Changed full width button to a rounded button

- ownCloud/Client/Actions/Actions+Extensions/UploadBaseAction.swift
- ownCloud/Client/Actions/Actions+Extensions/UploadPhotosAction.swift
- ownCloud/Client/ClientQueryViewController.swift
- ownCloud/Resources/en.lproj/Localizable.strings
- Offloaded photo import operations off the main thread
- Using fullsize image URL to derive filename
#365 
@felix-schwarz reported that UI thread is blocked while uploading a bunch of images.
@jesmrec reported in #365 that there are name conflicts on his device when uploading images from 'Screenshots' album.
____
Bugs & improvements:
> Fixing #365: Colliding names when uploading from Albums

- ownCloud/Client/ClientQueryViewController.swift
Added a chevron beside the navigation title, to show that title is actionable
#387 
Show the user, that navigation title is actionable
> Actionable navigation title

- ownCloud/Client/Viewer/DisplayViewController.swift
- ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift
- ownCloud/Resources/en.lproj/Localizable.strings
- Made DisplayViewController configurable in terms of adding more button
- Also replaced textual more (3 dots) symbol with corresponding icon
- Disabled display of more toolbar button in PDFViewerViewController
n.a.
More button from the parent class made goto button in PDF view invisible
> Fixed an issue with go-to button not being shown in PDF viewer

- .github/release_template.md
https://github.com/owncloud/ios-app/issues/368
The checklist in the release issue got improved over time. Now, changes should be added to the `release_template.md` to make future releases more efficient.
Tested with [1.0.1 release](https://github.com/owncloud/ios-app/issues/368)
> Bring learnings from 1.0.1 release to release_template.md

- ownCloud/Bookmarks/BookmarkInfoViewController.swift
Give the user a feedback, when offline copies will be deleted
#393 
Better user feedback
Account > Manage > Delete Offline Copies
Activity Indicator should appear right beside "Delete Offline Copies"
> Added an activity indicator for deleting offline copies

- ownCloud/Client/Sharing/GroupSharingTableViewController.swift
Fixed min length for searching a user or group in sharing view.
#454 
- Share File
- Search for a user or group
- Count letters, when activity indicator will appear for searching
- Check count result with server capability `user.search_min_length`
> [fix/sharing-search] Fixed min length for searching sharing users

- ownCloud/Client/Viewer/DisplayHostViewController.swift
- ownCloud/Client/Viewer/DisplayViewController.swift
Handling of moving / removal of pictures while browsing the gallery. See original PR for reference
#322
#447
> Fix for the PR #447 (keep gallery alive)

- docs/modules/ROOT/pages/ios_troubleshooting.adoc
Just link to a new page in the admin docs.
https://github.com/owncloud/ios-app/issues/341
Information about `X-REQUEST-ID` got added to the server admin docs in https://github.com/owncloud/docs/pull/1615 . This is very helpful to debug client issues.
```
git checkout docs/x-request-id-logs
git pull
cd docs
yarn install
yarn antora
yarn server
yarn serve
```
> Add link to information about X-REQUEST-ID

- ownCloud/Client/Sharing/PublicLinkEditTableViewController.swift
- ownCloud/UI Elements/StaticTableViewRow.swift
Checking`files_sharing.public.expire_date.expire_date.days` server capability. If it is set then it is used as default date and the switch is enabled even if the expiration date is not enforced.
#415 
See the issue description
>  Change behaviour of default expiration date

- ownCloud/Client/ClientItemCell.swift
As an user I want to see the end of a file name for a better differentiation for file name with the same prefix and which have a long file name.
#516
> [fix/filename-truncate-tail] Truncate middle of file name instead of tail

- ownCloud/Client/Actions/Actions+Extensions/CopyAction.swift
- ownCloud/Client/Actions/Actions+Extensions/DeleteAction.swift
- ownCloud/Client/Actions/Actions+Extensions/DuplicateAction.swift
- ownCloud/Client/Actions/Actions+Extensions/MoveAction.swift
- ownCloud/Client/Actions/Actions+Extensions/RenameAction.swift
- ownCloud/Client/Actions/Actions+Extensions/UnshareAction.swift
It was forgotten to return valid icon images for 'moreFolder' menu location.
#511 
Fixes inconsistency in the actions UI
Using the steps to reproduce described in the aforementioned issue.
> Fixed mission icons for ‘moreFolder’ location

- ownCloud File Provider/OCItem+FileProviderItem.m
Allows browsing of folders in the File Provider while in Airplane mode, with Files app no longer bringing up the "You're not connected to the Internet" error.
> [fix/fp-offline-browsing] Allow offline browsing of folders in the File Provider

- ownCloud File Provider/OCItem+FileProviderItem.m
Overrides UTIs for file formats where OS-based MIMEType conversion fails.
#557
> [fix/uti-conversion] work around broken MIMEType->UTI conversions in iOS

- ownCloud File Provider/FileProviderExtension.m
- ownCloud/Client/ClientRootViewController.swift
Fixes error and zero-sized documents when saving a document from Word.
https://github.com/owncloud/enterprise/issues/3642
> [fix/fp-word] Fix Word FileProvider issue

- ownCloud File Provider/FileProviderEnumerator.h
- ownCloud File Provider/FileProviderEnumerator.m
- ownCloud File Provider/FileProviderExtension.m
- ownCloud/FileLists/QueryFileListTableViewController.swift
This PR fixes an infinite loop when duplicating a folder in Files app. It also allows folder duplication via the Files app for the first time.
#550 (8)
> [fix/files-duplicate] Fix infinite loop when duplicating a Folder in Files app

- ownCloud/Client/Actions/ClientDirectoryPickerViewController.swift
Fixes to show the sort bar in the directory picker too.
#590 
Directory picker should also be present in this UI, because user needs this option for a faster navigating in this view.
- Move an item in the file list
- Sort Bar should be present in the Directory Picker, (Multi-)select button not present
> [feature/directory-picker-sort-bar] Show Sort Bar in Directory Picker

- ownCloud/Client/Sharing/PublicLinkEditTableViewController.swift
- ownCloud/Settings/LogFilesViewController.swift
Fixing sharing view on iPad for logfiles and public links
#606 
Sharing view on iPad was not fully visible
- Share a log file on the iPad
- Share a log file on the iPhone
- Share a public link on the iPad (in edit view from the toolbar item)
- Share a public link on the iPhone (in edit view from the toolbar item)
> [fix/sharingview-ipad] Broken Sharing View on iPad

- ownCloud/Client/ClientRootViewController.swift
Fixes UI restoration, when last opened path no longer exists
#601 
App unusable and user cannot get out of this app state
look at issue description
> [fix/stucks-in-blank-view] UI Restoration bug > App unusable

- ownCloud/Client/Library/LibraryTableViewController.swift
- ownCloud/Resources/en.lproj/Localizable.strings
This PR will add more famous mime types for the quick access collection
- `doc` as "Documents"
- `text/plain` as "Text"
- `video` as "Videos"
- `audio` as "Audio"
Quickly access files for special mime types
- add files with the mime type above to your oC account
- open account and navigate to "Quick Access"
- select collection with mime type and files will be inside
> [feature/quick-access-collections ] Expand Quick Access Collections

- ownCloud.xcodeproj/project.pbxproj
- ownCloud/Resources/Info.plist
- ownCloudAppShared/Intent/Base.lproj/Intents.intentdefinition
- ownCloudAppShared/Intent/SaveFileIntentHandler.swift
File could to be saved, when trying to save a file with Shortcuts and it already exists
#622 
Check Issue #622
> [fix/shortcut-save-file]

- ownCloud/Client/ClientRootViewController.swift
- ownCloud/UI Elements/Progress/ProgressSummarizer.swift
- ownCloud/UIKit Extensions/UIImageView+Thumbnails.swift
Fixes for a variety of offline issues:
How it could be reproduced:
- launch the app while in airplane mode
- log into an account
- open a folder, content is shown
- navigate back
- open the folder again, no content is shown
How it could be reproduced:
- create bookmark for large account
- log in and let the app start scanning the folders
- enable airplane mode
- go to "Status" tab and see the queue emptying
- log out
- disable airplane mode
- re-log in to the account
- see the lack of queued available offline items - or, if you're lucky - a slow, partial re-discovery
How it could be reproduced:
- create an account for an OAuth2 server with low token expiry time
- log in and log out
- enable airplane mode
- wait for the OAuth2 token to expire
- log back into the account while in airplane …
> [fix/offline] Fix various offline use bugs

- ownCloud/Client/Actions/Actions+Extensions/DocumentEditingAction.swift
- ownCloud/Client/Actions/EditDocumentViewController.swift
Fixes saving an edited markup file. When editing mode was not ended by the user, the delegate call with the changed file will be fired after the view was already dismissed.
Now will save this file, when it was not saved before.
#617 
#618 
Correct saving the edited file
- Markup a file
- Do not end editing mode
- Tap on `Done`
- Select a saving mode
- Changes are saved
> [fix/markup-saving] Fixes markup saving

- ownCloud/Licensing/Offers/LicenseOfferView.swift
Ensure equal font size for trial and subscription price in IAP/subscription card UI.
| Before | After |
----|----
> [fix/subscription-ui] Equalize subscription UI font size.

- fastlane/Fastfile
- fastlane/actions/app_version.rb
- fastlane/badge.svg
Fixed broken badge icon creation for fastlane builds. Added own action to set the build number and last git hash in the SVG image. Values are read from the project file.
#644 
Check Bitrise build for this branch, if it does not fail with the error message in the issue.
> [fix/fastlane-badge-icon] Fix for failing Bitrise builds on badge icon creation

- ownCloud/Client/ClientQueryViewController.swift
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/Settings/DisplaySettingsSection.swift
- ownCloudAppFramework/Display Settings/DisplaySettings.h
- ownCloudAppFramework/Display Settings/DisplaySettings.m
- ownCloudTests/SettingsTests.swift
Added a new setting to disable dragging inside the app. Changed the section name to `Advanced` to group more _advanced_ settings in this group.
#581 
Some users do not want to drag files inside the app. Also for accessibility it makes sense to disable this action for some users.
- Open Settings
- Scroll to `Advanced` section
- Disable `Drag files enabled`
- Open file list and try to drag a file
> [feature/drag-drop-setting] Setting to disable dragging files inside the app

- ownCloud File Provider/FileProviderExtension.m
- ownCloud/Client/Actions/EditDocumentViewController.swift
- ownCloudAppShared/Intent/SaveFileIntentHandler.swift
Fixes a problem, that completion handler may not be called and shortcut action finish with an error.
#651 
Correct handling of shortcut action
Look at issue description
> [fix/save-file-intent-completion] Fix for Save File Shortcut Completion

- ownCloud/Licensing/Offers/LicenseOfferButton.swift
- ownCloud/Theming/UI/ThemeButton.swift
- ownCloud/Theming/UI/ThemeRoundedButton.swift
Round shape for pin code buttons was lost after changes in superclass. Adopted the code to this changes.
#654
- set a pin code
> [fix/round-shape-button] Fix round shape for pin code buttons

- doc/CONFIGURATION.md
- ownCloud/FileLists/QueryFileListTableViewController.swift
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/Settings/DisplaySettingsSection.swift
- ownCloudAppFramework/Display Settings/DisplaySettings.h
- ownCloudAppFramework/Display Settings/DisplaySettings.m
- ownCloudAppShared/Client/SortMethod.swift
A new option in Settings to allow showing folders at the top of file lists.
#431
Test plan:
https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.4.0/Folders%20at%20the%20top.md
> [feature/folders-first] Option to show folders at the top

- ownCloud/Client/Actions/EditDocumentViewController.swift
- ownCloud/Client/Viewer/DisplayViewController.swift
- ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift
- When opening markup editor, it is immediately changing into editing mode eliminating the need for an extra tap on pencil icon
- When markup is opened from the file preview, file preview is re-rendered in case file was changed (by scribbling on PDF or image file for example)
- More button is added to PDF view allowing to take actions from within the PDF viewer
#729 
#698 
Adding more convenience and improving user experience
> Fixes for markup and PDF viewer

- ownCloud/Client/ClientQueryViewController.swift
- ownCloud/Client/PhotoSelectionViewController.swift
- ownCloud/Resources/en.lproj/InfoPlist.strings
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/Settings/DisplaySettingsSection.swift
- ownCloud/UI Elements/StaticTableViewRow.swift
Added delegate methods added to `UICollectionView` and `UITableView` allowing to enter-multiple selection mode with (two) finger pan.
Gestures:
- Two finger pan to start multiple selection of items in the file list
- In photo upload selection view, you can use one finger and pan over multiple items to select them.
- Gestures are iOS13 only and will work as long as "Prevent dragging of files and folders" option in settings is inactive
#725 
Saves few taps and allows select multiple items faster
> iOS13 gesture based multiple selection

- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/Settings/MoreSettingsSection.swift
Moved the app version informations in the app settings from the footer to a own table row to perform a row action.
If the user tap on this new row, the app informations will be copied to the clipboard. 
The user will see a notification banner, that the infos was copied to the clipboard.
#740 
This is important for bug reporting, to easily copy all needed informations to the clipboard.
- open app settings
- scroll to bottom
- tap on "App Version" row
> [feature/app-version-clipboard] App Version Infos to Clipboard

- ownCloud/Client/ClientQueryViewController.swift
- ownCloud/FileLists/FileListTableViewController.swift
- ownCloud/FileLists/QueryFileListTableViewController.swift
The following actions were missing in the file list, which is used in the `Quick Access` tab:
- Contextual Menu
- Multiple Selection (with toolbar)
- Cell swipe gesture (delete action)
This actions are missing, because this file list is the parent class of the general file list and the actions were defined in the child class. This PR moves the implementation into the parent class.
For me this is not a new feature, it is a bug fix. Most actions were implemented in this milestone and should also be available in all file lists.
#733 
As a user I want to have the same actions in the Quick Access file list like in the general file list.
Check if all mentioned actions are available in the general file list and in the Quick Access file list.
This actions should not be implemented in the `Pending …
> [fix/missing-file-list-actions] Implements missing actions in Quick Access file list

- docs/modules/ROOT/pages/ios_settings.adoc
This fixes a warning when compiling the docs:
```
asciidoctor: WARNING: ios_settings.adoc: line 78:
section title out of sequence: expected level 1, got level 2
```
The warning most likely appears because there is a blank line between the last cell and table end marker. Antora seems to gets confused by the blank line and thinks it is a new section which is out of sequence. It renders correct, but creates a warning. The blank line at the end in the table definition is now removed.
No warnings when compiling IOS docs
Compiling the docs locally
> Docs-only: fix "section title out of sequence" for table

- ownCloud File Provider/OCItem+FileProviderItem.m
Mime-Type to UTI fix for MindNode and iThoughtX documents in FileProvider. These file types were greyed out, because of a missing UTI.
Furthermore there is a fallback for file items with `pdf` extension, because a tester reported a problem, that pdf files are greyed out.
#747 
Access all file types inside the FileProvider
- Install MindNode, iThoughtX and create a document inside, save it to the FileProvider
- Close document
- Try to reopen this document inside the MindNode, iThoughtX app from FileProvider
> [fix/mime-type-uti] Added missing third party app UTIs

- ownCloud/Client/Library/Item Policies/ItemPolicyTableViewController.swift
In `Quick Access` > `Available Offline` > `All Files` there were all locally available files listed.
The correct behavior is, to show only available offline marked files.
#745 
Correct feedback to the user
- mark one ore more files/folders as `available offline`
- download other file items by viewing/downloading
- open `Quick Access` > `Available Offline` > `All Files`
- only files which are marked as `available offline` should be visible
> [fix/quick-access-available-offline] Quick Access: Only show available offline items

- ownCloud/Client/ClientQueryViewController.swift
- ownCloud/Client/SortBar.swift
- ownCloud/FileLists/QueryFileListTableViewController.swift
- ownCloud/Resources/en.lproj/Localizable.strings
New Label, which shows how many items are selected in the file list.
Give the user feedback how many items currently selected. Could also very handy, if all items are selected, how many items are inside this folder.
- Open file list
- Tap the `Select` button inside the sort bar
- Select one and more items
| ![Simulator Screen Shot - iPhone 11 Pro - 2020-08-06 at 13 51 24](https://user-images.githubusercontent.com/736109/89528919-23bc0600-d7ec-11ea-8781-560324533372.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-08-06 at 13 51 27](https://user-images.githubusercontent.com/736109/89528911-20c11580-d7ec-11ea-8c9c-06a59fe6b9c8.png) |
|---------------------------------------------------------------------------------------------------------------------------------------------------------- …
> [feature/selection-counter-label] File List: Selected items counter label

- ownCloud/Client/Actions/EditDocumentViewController.swift
Markup edit mode is not enabling automatically on iOS 14 devices.
iOS 13 and iOS 14 needs to be handled different in code.
#783 
Working functionality for early iOS 14 users
- Tap `Markup` for a document on iOS 13 iPhone
- Tap `Markup` for a document on iOS 13 iPad
- Tap `Markup` for a document on iOS 14 iPhone
- Tap `Markup` for a document on iOS 14 iPad
Result: Edit mode should be appear automatically
> [fix/markup-edit-mode-iOS14] Automatically enable Markup Edit Mode on iOS 14

- ownCloud/Client/ClientRootViewController.swift
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/Server List/ServerListTableViewController.swift
- ownCloud/Static Login/Interface/StaticLoginViewController.swift
- ownCloudTests/File List/FileTests.swift
Add error handling for the case where the start of an `OCCore` returns an error by displaying an alert. Previously, a partial UI was pushed - and remained in that state.
Kudos to @hosy for finding this code path!
#786 
To test, insert this code in `OCCoreManager.m:101`:
```objc
completionHandler(nil, OCError(OCErrorInternal));
return;
```
Tested with a faked internal error:
Before fix | After fix
-----------|------
> [fix/blank-screen] Fix issue where a blank screen is shown after selecting a bookmark

- ownCloud Share Extension/ShareViewController.swift
Saving attachments from iOS Mail.app was broken via the ownCloud share sheet, because of using the wrong type identifier when loading the file representation.
#816 
Correctly save any kind of attachment in iOS Mail.app via the ownCloud share sheet.
- try to save and kind of attachment from a mail via the share sheet (PDF, ZIP, ...)
- try to save the same file type from Files.app, to check this is not broken after the fix
> [fix/share-sheet-mail-attachments] Correctly save attachments from iOS Mail.app

- ownCloud/Client/Actions/Scanner/ScanViewController.swift
#822 
Faster change a file name in scan view, without deleting the file extension
- Scan document
- Save scanned page
- tap inside the filename text field
- (only) the filename should be selected
> [feature/scan-filename-selection] Selecting the Filename in Scan View

- fastlane/Fastfile
Set the Keychain Group for all targets when building with fastlane.
As an addition the badge creation was replaced with a fastlane action
https://github.com/owncloud/enterprise/issues/4272
Authentication error when performing actions via file provider because of wrong keychain group.
- create enterprise fastlane build `fastlane owncloud_enterprise_build`
- install IPA
- configure an basic auth account
- upload a file via app
- no authentication error should appear
> [fix/fastlane-set-keychain-group] Set Keychain Group for all targets in Fastlane Builds

- ownCloud.xcodeproj/project.pbxproj
- ownCloud.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ownCloud/AppDelegate.swift
- ownCloud/Resources/PLCrashReporter.LICENSE
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/Settings/MoreSettingsSection.swift
- adds a paragraph on top of the Acknowledgements to provide additional context
- adds PLCrashReporter license to acknowledgements
https://github.com/owncloud/enterprise/issues/4284
> [fix/ack-headers] Add paragraph on top of Acknowledgements page

- docs/modules/ROOT/pages/ios_accounts.adoc
- docs: change wording so it no longer suggests username is editable
- reported via RocketChat
> [fix/docs-edit-username] Docs: change wording so it no longer suggests username is editable

- ownCloud/Bookmarks/BookmarkViewController.swift
When editing bookmarks: 
- if a name was set, it wasn't shown in the edit interface
- bookmark name edits/additions would get lost
- bookmark name edits would not be presented in the list unless scrolling out of view and back in
> [fix/bookmark-name] Fix bookmark name editing

- ownCloudAppShared/Tools/AppStatistics.swift
- ownCloudAppShared/Tools/VendorServices.swift
- the first AppStore review request was changed from 14 days to 7 days after app installation
- the time interval between the next review request was changed from 230 days to 122 days
Present the App Store review panel more often to the user.
- please simulate the test like mentioned here: https://github.com/owncloud/ios-app/pull/728#issuecomment-645841323
- please test it on a device in real time (install app and check if the dialog appears after 7 days.)
> [fix/new-review-request] Improved AppStore Review Request Time

- .github/pull_request_template.md
- .github/workflows/calens.yml
- CHANGELOG.md
- changelog/CHANGELOG-Release.tmpl
- changelog/CHANGELOG.tmpl
- changelog/README.md
- changelog/TEMPLATE.txt
- changelog/unreleased/428
- changelog/unreleased/847
- changelog/unreleased/861
- semicolon_delimited_script
This PR uses GitHub Actions to automatically generate a changelog file with Calens and commits the new CHANGELOG.md into the current branch.
Furthermore the PR template was updated with new checkboxes to get sure, that a release notes issue file for Calense was added.
Automatically changelog file creation, with the same structure, as other ownCloud repositories.
- Add an release notes issue file into `changelog/unreleased` with the issue number as file name
- Commit and push to git
- Check GitHub Actions
- As a result the `CHANGELOG.md` file should be updated
> [feature/calens-changelog-actions] Automated Calens Changelog Creation

- ownCloud/Static Login/Interface/StaticLoginSetupViewController.swift
- ownCloud/Static Login/Interface/StaticLoginViewController.swift
- ownCloudAppShared/User Interface/Theme/NSObject+ThemeApplication.swift
1. UI fix for branded login on the iPad
2. Fill color for branded button was not used
1. https://github.com/owncloud/enterprise/issues/4367
2. https://github.com/owncloud/enterprise/issues/4366
Better UI experience
- Use a branded Client
- Test UI on iPad
- Test UI on iPhone
> [fix/branded-login-ipad-UI] Fixed Branded UI on iPad

- ownCloud/Settings/LogFilesViewController.swift
- ownCloudAppShared/Client/File Lists/ClientQueryViewController.swift
Fix drag and drop and improve support to run the iOS app on M1 Macs:
- add drag-out support for files that are not locally available yet
- improve drag-in support for files, picking the best available representation that can be retrieved as data
- support for drag & drop in the log file browser
> [feature/enhanced-drag-drop] Enhanced drag & drop support

- ownCloud/Client/Viewer/DisplayHostViewController.swift
- ownCloudAppShared/SDK Extensions/OCItem+Extension.swift
Fix for an issue when playing multiple items in the same directory. If e.g. image item is the next one, multi media playback would stop.
n/a
User would like to play all audio-visual files in a row without interruption.
> Fixing Media Player Behaviour

- docs/modules/ROOT/pages/ios_mdm.adoc
(table with Shortcuts parameter isn't autogenerated yet)
Fixes `asciidoctor: WARNING`:
```
% yarn antora
yarn run v1.22.10
$ antora --stacktrace generate --cache-dir cache --redirect-facility disabled --clean site.yml
asciidoctor: WARNING: ios_mdm.adoc: line 89: tag 'shortcuts' not found in include file: modules/ROOT/pages/ios_mdm_tables.adoc
✨  Done in 8.56s.
```
> Temporarily remove "Shortcuts" from MDM docs

- ownCloud/Settings/MoreSettingsSection.swift
- ownCloud/UI Elements/TextViewController.swift
Add `Themeable` support to the Acknowledgements, fixing the legibility issue in dark mode
Reported by @michaelstingl.
> [fix/acknowledgement-colors] Fix legibility of Acknowledgements in dark mode

- ownCloud/AppDelegate.swift
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/Tasks/UNUserNotificationCenter+Extensions.swift
- ownCloudAppFramework/Notifications/NotificationManager.h
- ownCloudAppFramework/Notifications/NotificationManager.m
- adds support for MDM setting hierarchies with flat keys
- simplified relaunch when receiving MDM setting updates
```json
{
"profiles$[0].index" 		 : 0,
"profiles$[0].name"  		 : "hello",
"profiles$[0].attributes.highlight"  : true,
"profiles$[0].nicknames[0]" 	 : "hi",
"profiles$[0].nicknames[2]" 	 : "howdy",
"profiles$[0].nicknames[1]" 	 : "hey",
"profiles$[1].index" 		 : 1,
"profiles$[1].name"  		 : "maxwell",
"profiles$[1].attributes.highlight"  : false,
"profiles$[1].nicknames[0]" 	 : "max",
"profiles$[1].nicknames[1]" 	 : "maxy",
"unrelated.settings.with.dots"	 : "oc"
}
```
After (transparent) expansion, this equals:
```json
{
"profiles" : [
{
"attributes" : {
"highlight" : 1,
},
"index" : 0,
"name" : "hello",
"nicknames" : [
"hi",
"hey",
"howdy"
]
},
{
"attributes" : {
"highlight" …
```
> [feature/flat-mdm-settings] Support for MDM setting hierarchies with flat keys

- CHANGELOG.md
- changelog/unreleased/905
- ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift
This PR changes the position of the PDF thumbnail view on the iPad from the bottom to the right position.
There are some reasons why the right position makes more sense:
- more visible (PDF) content, if the thumbnail view is on the right side
- if the thumbnail view is on the bottom, sometimes scrolling gesture activate the iOS app switcher
- open a PDF on the iPad
- thumbnail view should appear in landscape and portrait mode on the right side
- open a PDF on the iPhone
- thumbnail view should appear in landscape mode on the right, in portrait mode on the bottom
| Old version                                                                                                                                                                                  | Updated version …
> [fix/pdf-thumbnailview-position] PDF thumbnail view position on the iPad

- CHANGELOG.md
- changelog/unreleased/4432
- ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift
- Full screen mode in PDF view now requires to taps to hide bars
- Tap on link opens it in SFSafariViewController which runs as separate process.
- Now full screen mode requires two taps instead of one since otherwise tapping links won't be possible due to collisions with UIGestureRecognizer instances used by PDFView internally.
#4432
Opening links in PDF was not possible
> Accessing hyper links in PDF view

- ownCloudScreenshotsTests/ownCloudScreenshotsTests.swift
Changed the screenshot UI tests to support creating screenshots from branded builds like ownCloud.online.
Automatically generate UI screenshots from a branded build
- change variable `let takeBrandedScreenshots` to `true` in `ownCloudScreenshotsTests.swift`
- run fastlane with the following command: `fastlane release_on_appstore create_release_notes:false create_screenshots:true deliver:false build_regular_app:false build_emm_app:false build_owncloud_online_app:true`
> [feature/owncloud-online-screentshots] Create Screenshots for Branded Builds with Fastlane

- CHANGELOG.md
- changelog/CHANGELOG.tmpl
The Calens repo had some references inside the template, which pointed to the `client` repository. Furthermore the `milestone` branch pattern is used, instead of the `v` branch prefix.
- removed client repo with ios-app repo
- using milestone branch names, instead of v prefix
> [fix/calens-git-references] Fix Calens Git references

- fastlane/Fastfile
- ownCloud/Resources/Theming/Branding-owncloud-online.plist
- ownCloudAppShared/User Interface/Theme/ThemeCollection.swift
- ownCloudScreenshotsTests/ownCloudScreenshotsTests.swift
- updated toolbar / tab bar colors for ownCloud.online theme
- removed fixed secondary label color in light theme mode (which affects all branded themes)
- changed app name `ownCloud.online` to `ownCloud Online`
https://github.com/owncloud/enterprise/issues/4438
- build branded app
> [fix/oc-online-theme-colors] Updated ownCloud.online Toolbar /Tab Bar Color

- CHANGELOG.md
- changelog/unreleased/918
- ownCloud/Client/Viewer/DisplayHostViewController.swift
- disable page scrolling if less than two items inside the page view controller
- prevent page scrolling, when try to scroll inside the pdf thumbnail view on the iPhone
#918 
PDF Thumbnail View not working good 
- open PDF in detail view on and scroll inside the thumbnail view
- whole PDF view should not be scrollable
- open a folder with at least two images
- check if it is possible to scroll between images
> [fix/auto-page-scrolling] Auto Enable Page Scrolling in Detail View

- ownCloud/Bookmarks/BookmarkViewController.swift
- ownCloud/Server List/ServerListBookmarkCell.swift
- ownCloudAppFramework/SDK Extensions/OCBookmark+AppExtensions.m
Previously, the account list and auto-generated name used the redirect origin URL rather than the effective URL due to a [multi tenancy](https://github.com/owncloud/administration/tree/master/redirectServer) edge case. 
It now uses the effective URL:
- in the account list
- in the URL field of the edit bookmark view
- in the auto-generated `shortName` of the account
Client | Screenshot
------|------
Web | <img width="551" alt="O Connected to httpsocis ocis-traefik latest owncloud works as Albert Einstein" src="https://user-images.githubusercontent.com/639669/110548956-a665c480-8131-11eb-94e2-db006ad90fc6.png">
Android | ![Albert Einstein](https://user-images.githubusercontent.com/639669/110548926-9c43c600-8131-11eb-9790-01430f654a55.png)
iOS (before) | <img width="353" alt="Albert …
> [feature/align-bookmark-names] Align bookmark names with Android and web

- CHANGELOG.md
- changelog/unreleased/916
- ownCloudAppShared/User Interface/StaticTableView/StaticTableViewRow.swift
Fixed a problem in scan view when renaming the file name and using a Japanese keyboard layout (2-Byte character).
After entering a character inside the file name the text cursor jumped to the end.
#916 
Japanese keyboard support for all text input
- only testable on a real device
- add Japanese keyboard layout to the iOS keyboards
- Scan a document 
- Rename the file name inside the scan view
- please check if the following text fields working as expected: Public Link > Edit Link Name, Bookmark > Edit Bookmark Name
> [fix/japanese-input-support] Japanese Input Support

- CHANGELOG.md
- changelog/unreleased/919
- ownCloud/Client/Viewer/DisplayViewController.swift
- ownCloud/Client/Viewer/QuickLook/PreviewViewController.swift
Added Dark Mode Support for QLPreviewController
- added themeable protocol
- setting style in protocol and after init view
- moved themeable protocol of superclass from extension in class to override it in subclass
- added changelog issue
#919 
Provide dark mode support for all UI elements
Best test scenario:
- open two app instances side-by-side on the iPad
- open a text file on the left side
- open the theme app settings on the right side
- change theme setting to `Dark` > text view background should be dark
- change theme setting to `Classic` > text view background should be white
- change theme setting to `Light` > text view background should be white
- change theme setting to `System Appearance` > iOS setting: Light > text view background should be dark
- change theme setting to …
> [fix/qlpreview-dark-mode] Dark Mode Support for QLPreviewController

- ownCloud/Resources/Theming/Branding-owncloud-online-legacy.plist
- ownCloud/Resources/Theming/Branding-owncloud-online.plist
- ownCloudAppFramework/Branding/Branding.m
- ownCloudAppShared/Branding/Branding+App.swift
- ownCloudAppShared/Tools/VendorServices.swift
Added a new branding parameter to enable the app store review prompt. This setting is by default set to false, but if defined in Branding.plist or provided via MDM, the value can be overridden.
#939 
Needed for ownCloud online, but makes also sense to provide this parameter to other branded clients.
- build branded app for ownCloud online
- do the review time magic to test it
> [feature/branding-review-prompt] Enable App Store Review Prompt via Branding Parameter

- CHANGELOG.md
- changelog/unreleased/4468
- ownCloud/Client/Actions/Actions+Extensions/DocumentEditingAction.swift
- ownCloud/Client/Actions/EditDocumentViewController.swift
In some cases enabling markup mode failed. Now implemented a solution, which checks periodically, if the markup button is available, before enabling. Furthermore implemented a check, if item could be previewed in markup action and shows an error, if not possible.
https://github.com/owncloud/enterprise/issues/4467
https://github.com/owncloud/enterprise/issues/4468
Enable markup mode reliable
Open a PDF or image file in markup mode.
Please test on iPad and iPhone, iOS 14 and iOS 13
> [fix/enable-markup-editing] Improved Enabling Markup Mode

- ownCloud/Resources/Theming/Branding-owncloud-online-legacy.plist
- ownCloud/Resources/Theming/Branding-owncloud-online.plist
- ownCloud/Resources/de.lproj/Localizable.strings
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloud/Static Login/StaticLoginProfile.swift
Made some branded profile configuration login parameter optional for localization.
If the keys does not exists, the default localization string will be used.
https://github.com/owncloud/enterprise/issues/4501
Provide localized branded login screen
- build a  branded app (ownCloud Online)
- check if localization change in login screen, if switching to other language (at the moment only German translation is available)
- add these keys to the `Branding.plist`: `welcome` `promptForPasswordAuth` `promptForTokenAuth` `promptForURL`
- Enter your own values for these keys
- Run app and check branded login screen, if strings will be used
Checks performed [here](https://github.com/owncloud/ios-app/pull/948#issuecomment-823156837)
> [feature/branded-login-localization] Localized Branded Login 

- CHANGELOG.md
- changelog/unreleased/952
- ownCloud/Client/Actions/Actions+Extensions/DocumentEditingAction.swift
Images with mime type `image/gif` can not edited with markup action and needs to be disabled.
#952
Only show possible actions to the user
- add an image with mime type `image/gif` to the file list 
- check if action `Markup` is not available
> [fix/disable-gif-markup] Disable Markup Action for Mime-Type Gif

- CHANGELOG.md
- changelog/unreleased/956
- ownCloudAppShared/User Interface/Card Presentation Controller/CardPresentationController.swift
- ownCloudAppShared/User Interface/More/FrameViewController.swift
Made some UI refinements to the cardview controller:
- fixed the corner radius (was gone in a version before)
- for larger UI width set a maximum width for the cardview and center the view
UI Fetish
- open the more menu for an item
- rotate the device
- check on iPhone and iPad
- on iPad place two windows side by side and change the window size and rotate the screen
| ![Simulator Screen Shot - iPad Air (4th generation) - 2021-04-27 at 13 28 29](https://user-images.githubusercontent.com/736109/116234578-13263400-a75d-11eb-86ce-5dadffbf0002.png) | ![Simulator Screen Shot - iPad Air (4th generation) - 2021-04-27 at 13 28 05](https://user-images.githubusercontent.com/736109/116234572-115c7080-a75d-11eb-95cd-4db06241b14e.png) |
|------------------------------------------------------------------ …
> [fix/cardview-ui-refinement] Cardview UI Refinements

- CHANGELOG.md
- changelog/unreleased/957
- ownCloud/SceneDelegate.swift
- ownCloud/Server List/ServerListTableViewController.swift
- ownCloud/Static Login/Interface/StaticLoginViewController.swift
State restoration was not working for branded clients.
#957 
Reopen last used items after an app restart.
- open an item 
- set app to background
- force quit app
- restart app
- as a result the last shown item should be reopened
- on the iPad: all windows should be reopened with the last items
Please test this steps in the regular unbranded app and for a branded client like ownCloud Online
> [fix/branded-state-restoration] Branded Login State Restoration

- changelog/unreleased/986
- ownCloud File Provider UI/DocumentActionViewController.swift
Views in file provider UI (public links, share with user) could not be dismissed on iOS 12
#986 
- follow instructions described in issue
- repeat the same on iOS 13, 14
> [fix/ios12-share-sheet] File Provider UI: Dismiss View on iOS 12

- CHANGELOG.md
- changelog/unreleased/979
- fastlane/Fastfile
When building the apps (regular, EMM, oc.online) with fastlane, an additional app URL-Scheme will be added to the `Info.plist` file.
regular: `owncloud-app`
EMM: `owncloud-emm`
oc.online: `owncloud-online`
With this app specific URL scheme, the user can decide which app should be opened, if more than one of this apps is installed on the system.
#979 
- open Safari
- run `bundle exec fastlane owncloud_emm_build`
- enter in URL bar: owncloud-emm://demo@owncloud.com/f/6
- ownCloud EMM app should be opened
> [feature/additional-url-scheme] Added Additional URL Scheme

- fastlane/Fastfile
This PR implements to set the Drone build number in fastlane (in ownBrander Builds) as `CFBundleVersion` for all app targets.
Furthermore the build number will be added to the output IPA filename.
- every ownBrander build can be identified inside the app settings
- AppStore needs an unique build number for every new upload
- Trigger a new ownBrander build
- Install IPA
- check build number in app settings
> [feature/drone-build-number] Use Drone Build Number as CFBundleVersion

- ownCloud/Static Login/Interface/StaticLoginSetupViewController.swift
- ownCloud/Static Login/StaticLoginProfile.swift
Makes the onboarding section available for the branded login, if `can-add-account` it `true` or `false`.
#1007
> [fix/branding-login-onboarding-section] Branded Login: Onboarding Section

- enterprise/resign/README.md
- enterprise/resign/resignOwncloudApp
Resign script can now inject associated domains into the resigned application's entitlements.
Store a text file `domains.txt` in the `/enterprise/resign` folder and run the resign script.
> Added associated domains to resign script

- CHANGELOG.md
- changelog/unreleased/4558
- ownCloud/Static Login/Interface/StaticLoginViewController.swift
- ownCloud/Tools/URL+Extensions.swift
- ownCloud/UIKit Extensions/UIWindow+Extension.swift
This PR fixes a bug, when trying to open a private link via the custom url scheme `owncloud://` or via associated domains `applinks:`.
Now after resolving the private link the file will be opened in detail view.
This PR also fixes a possible deadlock, when trying to retrieve an item for a link.
#1031
Check the issue for reproducing
> [fix/open-private-link-branding] Open Private Link in Branded Client

- enterprise/resign/README.md
- enterprise/resign/resignOwncloudApp
- ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift
Issue details mentioned in #1033
#1033
Issue #1033have details of this issue
I have tested with the steps given in issue#1033
> #1033 - In pdf preview, Go to Page don't take user to last page

- ownCloud/Client/Actions/EditDocumentViewController.swift
This is a fix for enabling the markup edit mode on iOS 15, which was broken there, because a new bar button is available there.
#1012 
Non working feature on iOS 15
- Select `Markup` action on a PDF or Image
- Markup feature should be enabled automatically
- Test on iOS 13, iOS 14 and iOS 15
> [fix/markup-ios15 ] Enabling Markup Edit Mode on iOS 15

- .swiftlint.yml
- ownCloudAppFramework/Branding/Branding.h
- ownCloudAppFramework/Branding/Branding.m
- ownCloudAppFramework/Branding/BrandingClassSettingsSource.m
- ownCloudAppShared/Foundation Extensions/String+Extension.swift
- ownCloudAppShared/Tools/VendorServices.swift
Switches `OCLocalized`, `OCLocalizedString` and `String.localized` from `NSLocalizedString` and `NSBundle` to `OCLocale`, allowing complex customization of localized strings with variables, value sources and complete text replacements.
That makes it possible to change the localization of specific strings via class settings. To f.ex. change `Settings` to `Preferences` (en) and `Präferenzen` (de), one would use:
```xml
<key>locale.overrides</key>
<dict>
<key>Settings</key>
<dict>
<key>en</key>
<string>Preferences</string>
<key>de</key>
<string>Präferenzen</string>
</dict>
</dict>
```
Furthermore, localized strings can now contain variables that are getting replaced during localization.
For example:
```swift
Log.log("{{app.name}} {{app.process}} {{app.version}} {{app.build}} {{device.model}} …
```
> [feature/modular-localization] Modular localization

- ownCloud/SceneDelegate.swift
- ownCloud/Server List/ServerListTableViewController.swift
- ownCloud/Static Login/Interface/StaticLoginSetupViewController.swift
- ownCloud/Static Login/Interface/StaticLoginViewController.swift
Skip "Manage" screen / automatically open "Files" screen after login via MDM parameter
https://github.com/owncloud/enterprise/issues/4801
Skip the account screen automatically.
- configure branded app
- set parameter `account.auto-connect` with value `true` via MDM or `Branding.plist`
> [feature/mdm-auto-connect] Skip Account Screen via MDM

- ownCloudAppFramework/AppLock Settings/AppLockSettings.h
- ownCloudAppFramework/AppLock Settings/AppLockSettings.m
- ownCloudAppShared/AppLock/PasscodeSetupCoordinator.swift
- Control via MDM/Branding parameter to auto enable biometrical unlock
- Immediately show Face ID authorization after the feature was enabled
https://github.com/owncloud/enterprise/issues/4818
Enable biometrical unlock automatically:
```
<key>passcode.use-biometrical-unlock</key>
<true/>
```
Default behavior, if not set via MDM or `Branding.plist`:
Show alert and suggest to enable biometrical unlock
```
<key>passcode.use-biometrical-unlock</key>
<false/>
```
Checks: https://github.com/owncloud/ios-app/pull/1058#issuecomment-947724112
> [feature/mdm-biometrical-unlock]  MDM setting for Biometrical Unlock

- ownCloud/Settings/AutoUploadSettingsSection.swift
- ownCloud/Settings/MediaUploadSettingsViewController.swift
- ownCloudAppShared/User Interface/StaticTableView/StaticTableViewController.swift
Do not show the `Background Location` settings section, if no upload path was chosen.
#1050 
[UX] Only show settings to the user, which can be enabled.
- open `Media Upload` settings
- `Background Location` settings section should only be visible, if a upload path was chosen 
Reports:
> [feature/hide-background-location-settings] Do not show Background Location section by default

- ownCloudAppShared/AppLock/AppLockManager.swift
Clear `unlock` and `lastApplicationBackgroundedDate` in `AppLockManager` in case an unlock has expired, to protect against subsequent attempts setting the device time to an earlier date.
Previously, only the `unlock` value was reset.
Also clears `unlock` and `lastApplicationBackgroundedDate` in `AppLockManager` and logs a security warning in case device time precedes `lastApplicationBackgroundedDate`.
> [fix/clear-lock] Clear lock when determining unlock expiry

- ownCloudAppShared/Client/User Interface/SortMethod.swift
This PR changes sorting to use localized sorting across query results and database queries, via the SDK's new `OCLOCALIZED` collation and sort comparator.
What was previously 
`1`, `100`, `11`
now becomes 
`1`, `11`, `100`.
#975
> [feature/sort-order] Localized sort order

- CHANGELOG.md
- changelog/unreleased/4857
- ownCloudAppShared/User Interface/Theme/ThemeCollection.swift
Use the corporate color as folder color as default color (can be overridden by the specific key/value pair).
[1069](https://github.com/owncloud/ios-app/issues/1069)
Reduce default branding configuration by setting the corporate color by default.
Copy a `Branding.plist` only with the minimal color set into the project and build the app.
Check, if the folder was colored with the corporate color.
Set the corporate color:
```
<key>branding.theme-definitions$[0].darkBrandColor</key>
<string>#DD00DD</string>
```
Set the folder fill color:
```
<key>branding.theme-definitions$[0].Colors.Icon.folderFillColorr</key>
<string>#DD00DD</string>
```
Please check if everything is working fine, with the unbranded app (dark, light, contrast).
> [fix/branding-folder-color] Branding: Corporate Color as Folder Color

- CHANGELOG.md
- changelog/unreleased/4924
- ownCloud/Client/Viewer/DisplayHostViewController.swift
- ownCloud/Client/Viewer/Media/MediaDisplayViewController.swift
Fixed continuous audio playback, which stopped, after two audio files, because of not setting the `activeDisplayViewController`, when starting a new audio file
https://github.com/owncloud/enterprise/issues/4924
Play continuous all audio files in a folder
- Put some audio files (at least 3 files) in a folder
- Select the first audio file
- The new audio file should start playing, when the current has finished
> [fix/continuous-audio-playback] Fix: Continuous Audio Playback

- CHANGELOG.md
- changelog/unreleased/972
- ownCloud/Bookmarks/BookmarkViewController.swift
- ownCloud/Server List/ServerListTableViewController.swift
- ownCloud/Static Login/Interface/StaticLoginSingleAccountServerListViewController.swift
Check if only the account name was changed in edit mode: save and dismiss without re-authentication
#972 
Easier account editing, without annoying the user with re-authentication
- Edit existing account
- Change name
- Tap on `Continue`
- View should be dismissed without authentication flow
- Try again with changing the URL or only changing the URL
- Authentication should now happen
Reports:
> [feature/rename-accounts] Rename Account without Authentication Flow

- ownCloudAppShared/AppLock/AppLockManager.swift
- ownCloudAppShared/AppLock/PasscodeSetupCoordinator.swift
- ownCloudAppShared/AppLock/PasscodeViewController.swift
Fix for passcode setup with biometrical unlock enabled:
- biometrical unlock button no longer appear in setup view
- after passcode was successfully setup, show biometrical unlock for permissions dialog
https://github.com/owncloud/enterprise/issues/5086
- do not show UI elements, which are not available in a context 
- show permission dialog in setup context
- Test setting up passcode with biometrical unlock in unbranded client
- Test in branded client (use the code below in `Branding.plist`)
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>branding.organization-name</key>
<string>Demo</string>
<key>branding.profile-bookmark-name</key>
<string>Demo</string> …
```
> [fix/biometrical-unlock-setup] Fix: Setup Passcode with Biometrical Unlock

- ownCloud.xcodeproj/project.pbxproj
- ownCloud.xcworkspace/xcshareddata/swiftpm/Package.resolved
With Apple Silicon M1 it was no longer possible to build the app for Simulator.
Because we need to provide additional architecture, we using new OpenSSL as Swift package.
In the context of this, the code was migrated to OpenSSL 1.1.1.
- migrated code to new OpenSSL 1.1.1 API
- using OpenSSL Swift Package
Build against all architectures, using the latest OpenSSL version.
- Build and run on all platforms iOS, Mac Catalyst, Simulator, Device
- Add a new account
- Check if certificate output is the same as before migrating
Checklist: https://github.com/owncloud/ios-app/pull/1116#issuecomment-1091647029
Reports
> [feature/openssl-1.1.1] Migration to OpenSSL 1.1.0

- ownCloudAppFramework/Licensing/Providers/EMM/OCLicenseEMMProvider.m
If app is build as EMM version, the app shows an licensing error, when running shortcut intents (could not read app bundle identifier in extension)
#1114 
EMM version should not show or restricted by licensing
- Build EMM version (use `fastlane owncloud_emm_build` for setting the app identifier)
- In `Shortcuts.app` create a new shortcut and add an ownCloud EMM action
- Running should not show an licensing error
> [fix/shortcut-emm-licensing] EMM Shortcuts Licensing

- ownCloud Intents/Base.lproj/Intents.intentdefinition
Account options were not dynamically provided for action "Delete Account Item", because of wrong intent configuration
#1123 
- In Shortcuts:
- Add action `Delete Path Item`
- Try to select an configured account
> [fix/shortcuts-delete-path-item-accounts] Shortcuts: Delete Path Item - No Accounts provided

- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud.xcscheme
- increase HTTP request timeout for `COPY` actions from 1 minute to 10 minutes
- improve error handling for request timeouts
Addresses https://github.com/owncloud/enterprise/issues/5008 .
> [fix/copy-timeout] Fix copy timeout

- ownCloud Share Extension/Info.plist
- ownCloud Share Extension/ShareNavigationController.swift
- ownCloud Share Extension/ShareViewController.swift
- ownCloud.xcodeproj/project.pbxproj
- ownCloudAppFramework/AppLock Settings/AppLockSettings.h
- ownCloudAppFramework/AppLock Settings/AppLockSettings.m
- ownCloudAppFramework/Branding/Branding.h
- ownCloudAppFramework/Branding/Branding.m
- ownCloudAppFramework/UIKit Extensions/UIViewController+HostBundleID.h
- ownCloudAppFramework/UIKit Extensions/UIViewController+HostBundleID.m
- ownCloudAppFramework/ownCloudApp.h
- ownCloudAppShared/AppLock/AppLockManager.swift
- ownCloudAppShared/AppLock/PasscodeViewController.swift
- ownCloudAppShared/UIKit Extension/UIViewController+Extension.swift
Workaround for fixing the biometrical unlock in the share sheet, when opening from Boxer app. View disappeared after the biometrical unlock succeeded. Probably because 'completeRequest' was sent from the biometrical unlock extension, which caused a dismiss in the share sheet extension.
https://github.com/owncloud/enterprise/issues/5256
**For a description of the current implementation, please see https://github.com/owncloud/ios-app/pull/1129#issuecomment-1183692817.**
For the previous implementation details, please expand the element below:
<details>
Use a branded client for testing and add the following parameters to the `Branding.plist` file:
```
<key>passcode.enforced</key>
<string>true</string>
<key>passcode.lockDelay</key>
<integer>60</integer> …
```
> [fix/share-sheet-biometrical-unlock] Biometrical Unlock in Share Sheet

- ownCloud/Static Login/Interface/StaticLoginSetupViewController.swift
- ownCloudAppShared/UIKit Extension/UIColor+Extension.swift
- ownCloudAppShared/User Interface/Theme/NSObject+ThemeApplication.swift
- ownCloudAppShared/User Interface/Theme/ThemeCollection.swift
Fix some automatic color values, if the branding color is bright. Before we only had a look if the branding color is white, but this does not work. Introduced a new welcome style for informal button, because the general informal button color does not work for the login screen in all cases
https://github.com/owncloud/enterprise/issues/5199
> [fix/bright-branding-color] Branding: Color issues

- CHANGELOG.md
- changelog/unreleased/1141
- changelog/unreleased/1146
- ownCloud/Client/ClientRootViewController.swift
- ownCloud/Resources/en.lproj/Localizable.strings
- ownCloudAppShared/User Interface/Theme/NSObject+ThemeApplication.swift
- ownCloudAppShared/User Interface/Theme/ThemeStyle+DefaultStyles.swift
- ownCloudAppShared/User Interface/Theme/ThemeStyle+Extensions.swift
- ownCloudTests/SettingsTests.swift
Adds a new dark mode theme which is mostly equal to the web UI dark mode theme.
Furthermore it adds a black dark mode theme.
It also fixes a bug when a new theme was activated, this causes that the `UITabBar` and `UIToolbar` does not updates colours.
Theme: https://github.com/owncloud/ios-app/issues/1146
Colour Bug: https://github.com/owncloud/ios-app/issues/1141
- Go to Settings > Theme
- Select `Dark Web`
or
- Select `Dark Black`
On iPad:
- Go to file list
- Hit the keyboard command `Option (Alternate)` + `T`
- Active theme should change to the next theme
- Please check, if `TabBar` and `Toolbar` colour changes to the correct value (`Toolbar` can be checked in file list selection mode)
| **Dark Web** …
> [feature/theme-dark-web] New Dark Mode Themes

- ownCloudAppShared/Client/Sharing/PublicLinkTableViewController.swift
Respect `files.privateLinks` capability and do not offer to create private links when privateLinks are not supported.
https://github.com/owncloud/ios-app/issues/1138
Before | After
-------|--------
> [fix/private-links-capability] Respect privateLinks capability

- CHANGELOG.md
- changelog/unreleased/1141
- ownCloud/Client/Actions/EditDocumentViewController.swift
Enabling markup mode was broken on iOS 16 because of rearranged navigation bar and toolbar items.
#1141 
Enable markup mode automatically after selecting the action.
- Select action `Markup` on a PDF or Image file
- Markup UI should be visible
> [fix/enable-markup-iOS16] Enabling Markup Mode on iOS 16

- ownCloud/Client/Viewer/Media/MediaDisplayViewController.swift
Fixes AVPlayerViewController controls not being visible on iOS 16 (finding "iOS 3" in https://github.com/owncloud/ios-app/issues/1141#issuecomment-1224289367)
#1141
> [fix/ios-16-media-controls] Fix missing iOS 16 video controls

- CHANGELOG.md
- changelog/unreleased/1156
- ownCloud Share Extension/ShareViewController.swift
- ownCloudAppShared/AppLock/AppLockManager.swift
The passcode lock interval was not taken into use in the share extension.
Background and foreground state is not possible in share extensions. Date will now be saved by triggering the mode manually.
#1154
Working passcode lock interval in share extension.
Have a look at the issue
> [fix/share-extension-passcode-lock-interval] Share Extension Passcode Lock Interval

- ownCloudAppShared/Client/Data Item Interactions/OCShare+Interactions.swift
- ownCloudAppShared/Client/Sharing/ShareViewController.swift
Fixed overlapping sharing buttons
[#5815 ](https://github.com/owncloud/enterprise/issues/5815)
> [fix/overlapping-sharing-buttons] Overlapping Sharing Buttons

- ownCloudAppShared/Client/View Controllers/ClientSidebarViewController.swift
Removed the logo label from the sidebar navigation bar to have more space for the logo image
https://github.com/owncloud/enterprise/issues/5809
Customers with a wide logo needs more space in the navigation bar. 
The logo label was a duplicated information.
> [fix/sidebar-logo] Sidebar Logo

- CHANGELOG.md
- ownCloudAppShared/Client/Collection Views/Cells/UniversalItemListCell Content Providers/OCShare+UniversalItemListCellContentProvider.swift
- ownCloudAppShared/Client/Collection Views/Cells/UniversalItemListCell Content Providers/OCShareRole+UniversalItemListCellContentProvider.swift
- ownCloudAppShared/Client/Collection Views/Cells/UniversalItemListCell.swift
- ownCloudAppShared/Client/Sharing/ShareViewController.swift
Adds a `Name` field for link shares, allowing to enter and edit the name of link shares.
#1246 
Create | Edit
----|-----
> [feature/link-naming] Link naming

- CHANGELOG.md
- ownCloud/Client/Actions/Actions+Extensions/CreateDocumentAction.swift
- ownCloud/Client/Actions/Scanner/ScanViewController.swift
- ownCloudAppShared/Client/User Interface/NamingViewController.swift
- ownCloudAppShared/User Interface/StaticTableView/StaticTableViewRow.swift
- ownCloudAppShared/User Interface/Theme/CSS/Views/ThemeCSSTextField.swift
Prevents users from removing or changing the suffix for:
#1292
> [feature/suffix-protection] File extension / suffix protection

- ownCloud File Provider/FileProviderExtension.m
- ownCloud File Provider/FileProviderExtensionThumbnailRequest.m
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud File Provider.xcscheme
This branch addresses found issues in the File Provider:
- fixes unanswered thumbnail requests (leading to infinite thumbnail responses)
- fixes incorrect error being returned in response to thumbnail requests
> [fix/fp-fixes] File Provider fixes

- ownCloud/Client/Actions/EditDocumentViewController.swift
Fixed disabling edit mode in markup document view on iOS 17. The previous implementation is no longer working on iOS 17.
Problem was, that the edit mode was not disabled automatically. This prevents dismissing and saving the view.
- https://github.com/owncloud/enterprise/issues/6253
Save edited PDF file.
- Open iOS App 
- open a PDF File in Markup mode
- write or draw something
- click on "Done"
- choose "Overwrite original" or "Save as copy"
- view should be dismissed and changes saved
> [fix/disable-edit-mode-ios17] Disable Markup Edit Mode iOS 17

- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud.xcscheme
- ownCloudAppShared/Client/Actions/Action.swift
- ownCloudAppShared/Client/Collection Views/Cells/UniversalItemListCell Content Providers/OCItemPolicy+UniversalItemListCellContentProvider.swift
- ownCloudAppShared/Client/Collection Views/Cells/UniversalItemListCell Content Providers/OCShare+UniversalItemListCellContentProvider.swift
- ownCloudAppShared/Client/Data Item Interactions/OCLocation+Interactions.swift
- ownCloudAppShared/Client/View Controllers/ClientItemViewController.swift
- ownCloudAppShared/Client/View Controllers/Location Breadcrumbs/OCLocation+Breadcrumbs.swift
- ownCloudAppShared/Client/View Controllers/Location Picker/ClientLocationPicker.swift
- ownCloudAppShared/User Interface/More/MoreViewHeader.swift
Fix an issue arising from Available Offline policies targeting unavailable/detached drives and removes the respective policies.
> [fix/available-offline-policy-cleanup] Fix cleanup of Available Offline policies targeting unavailable spaces

- CHANGELOG.md
- PrivacyInfo.xcprivacy
- changelog/12.2.0_2024-04-23/1348
- ownCloud.xcodeproj/project.pbxproj
Adds the [privacy manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc) [required by Apple starting May 1, 2024](https://developer.apple.com/news/?id=3d8a9yyh) to the app and upgrades `krzyzanowskim/OpenSSL` to [3.1.5001](https://github.com/krzyzanowskim/OpenSSL/releases/tag/3.1.5001) to include a privacy manifest as [also required by Apple](https://developer.apple.com/support/third-party-SDK-requirements/).
~Note: since changes to the `ios-sdk` are also needed, this PR is based on [feature/url-shortcuts](https://github.com/owncloud/ios-app/tree/feature/url-shortcuts) which adopts the latest `ios-sdk` API changes. It's target should be changed to `milestone/12.3` once `feature/url-shortcuts` has been …
> [feature/privacy-manifests] Add required privacy manifests

- .github/workflows/translate.yml
Fixed duplicated nested directories after tx pull and broken git commit
> [fix/github-translation-action] Fix nested translation pull

- ownCloud Share Extension/ShareExtensionViewController.swift
- ownCloud.xcodeproj/project.pbxproj
- ownCloud.xcodeproj/xcshareddata/xcschemes/MakeTVG.xcscheme
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud File Provider.xcscheme
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud File ProviderUI.xcscheme
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud Intents.xcscheme
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud Share Extension.xcscheme
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud.xcscheme
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloudApp.xcscheme
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloudScreenshotsTests.xcscheme
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloudTests.xcscheme
- ownCloud/App Controllers/AccountController+ExtraItems.swift
- ownCloud/App Controllers/AccountController+ItemActions.swift
- ownCloud/AppDelegate.swift
- ownCloud/SceneDelegate.swift
- ownCloud/Tools/VendorServices+App.swift
- ownCloudAppShared/Branding/Branding+App.swift
- ownCloudAppShared/Intent/OCLicenseManager+Setup.swift
- ownCloudAppShared/Tools/Log.swift
- ownCloudAppShared/UIKit Extension/UIView+OCDataItem.swift
- ownCloudAppShared/User Interface/View Providers/OCResourceText+ViewProvider.swift
This PR contains fixes to make the app run on iOS/iPadOS 18 and Xcode 16.
**Temporarily targets #1351 instead of `master` to allow seeing only the changes until that branch is merged to `master`.**
#1371
> [fix/xcode-16] Fixes for iOS/iPadOS 18 and Xcode 16

- ownCloud File Provider/FileProviderExtension.m
- ownCloud.xcodeproj/project.pbxproj
- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud File Provider.xcscheme
- ios-sdk: update to fix/fp-memory branch to reduce memory consumption further
- FileProviderExtension: remove CrashReporter framework to lower memory consumption
- ownCloud File Provider.xcscheme: remove stack logging debug option to lower memory consumption enough to make the extension actually debuggable again
#1362
> [fix/fp-memory] Reduce FP memory consumption

- Gemfile
GitHub dependabot cannot analyse the Gemfile due to error below
Error message:
```
Dependabot only supports uninterpolated string arguments to eval_gemfile. Got `plugins_path`
```
Allow GitHub dependabot to manage dependencies
> fix: simplify Gemfile to allow GitHub dependabot to parse this file properly

- ownCloud.xcodeproj/project.pbxproj
This pull request includes changes to the `ownCloud.xcodeproj/project.pbxproj` file to fix it for fastlane builds for EMM and oC.online builds.
Before the fix the wrong provisioning profile was used.
* Set `DEVELOPMENT_TEAM` directly and removed redundant `DEVELOPMENT_TEAM[sdk=iphoneos*]` entry.
* Set `PROVISIONING_PROFILE_SPECIFIER` directly and removed redundant `PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]` entry.
#1438
> [fix/fastlane-build-action-extension-provisioning] Fixed fastlane builds for EMM and oC.online

- ownCloudAppShared/Client/Sharing/ShareViewController.swift
- ShareViewController: add support for new "block password removal" capabilities
https://github.com/owncloud/ios-app/issues/1429
> [feature/security-first] Add capability control to allow password removal independent of password enforcement

- ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud.xcscheme
Adds a MDM/branding control over block_password_removal default value and reverts the default to the previous behavior.
`connection.block-password-removal-default`
> If a server does not provide `block_password_removal` information as part of its capabilities, this option provides the fallback value controlling whether passwords can (value: false) or can not (value: true) be removed from an existing link even if capabilities otherwise indicate passwords need to be enforced for links.
To implement the behavior as requested in #1429, `connection.block-password-removal-default` needs to be set to `false` in the `Branding.plist`:
```xml
<key>connection.block-password-removal-default</key>
<false/>
```
#1429 -- SDK portion: https://github.com/owncloud/ios-sdk/pull/139
> [feature/security-first-mdm] Add MDM/branding control over block_password_removal default value

- ownCloudAppShared/Client/Collection Views/Cells/DriveHeaderCell.swift
- ownCloudAppShared/Client/Collection Views/Cells/DriveListCell.swift
- ownCloudAppShared/UIKit Extension/UICellAccessory+Extension.swift
- ownCloudAppShared/UIKit Extension/UIColor+Extension.swift
- ownCloudAppShared/User Interface/Theme/ThemeCollection.swift
- ThemeCollection: remove superfluous code cell
- DriveListCell: hide subtitle label if subtitle is not set or empty
- DriveHeaderCell: make sensitive to high contrast mode, adding a dark background if detected or changed to
#1334
> [fix/a11y-1334] Add Spaces text background color if Increase Contrast is on

- ownCloudAppFramework/Foundation Extensions/NSURL+OCVaultTools.m
Fixes a crash when using the iOS app on macOS and dropping a file onto the app's window to upload a file.
> [fix/mac-drop-crash] Fix file drop crash on macOS

- ownCloud/Client/Viewer/QuickLook/PreviewViewController.swift
- ownCloud/Client/Viewer/WebView/WebViewDisplayViewController.swift
PreviewViewController/WebViewDisplayViewController: if watermark/confidential overlays are used, QLPreviewController no longer reacts to scroll and zoom events, so use WebKit's support for QuickLook formats instead in those cases.
Testing note: test with multi-page/multi-slide documents to reproduce the issue.
https://github.com/owncloud/enterprise/issues/7224
> [fix/confidential-office-pan-zoom] Fix pan/zoom issue when using confidential overlay options

- .swiftlint.yml
- ownCloud.xcodeproj/project.pbxproj
- ownCloud/Resources/Localizable.xcstrings
- ownCloudAppShared/Client/Collection Views/CollectionViewCellProvider+StandardImplementations.swift
- ownCloudAppShared/Client/View Controllers/Location Breadcrumbs/OCLocation+Breadcrumbs.swift
- ownCloudAppShared/Client/View Controllers/Location Picker/ClientLocationPicker.swift
- ownCloudAppShared/Client/View Controllers/Location Picker/Recent Location/RecentLocation+Interactions.swift
- ownCloudAppShared/Client/View Controllers/Location Picker/Recent Location/RecentLocation+UniversalItemListCellContentProvider.swift
- ownCloudAppShared/Client/View Controllers/Location Picker/Recent Location/RecentLocation.swift
- ownCloudAppShared/Client/View Controllers/Location Picker/Recent Location/RecentLocationCell.swift
- ownCloudAppShared/Client/View Controllers/Location Picker/Recent Location/RecentLocationStore.swift
- ownCloudAppShared/User Interface/SegmentView/SegmentViewItemView.swift
- ownCloudAppShared/User Interface/Theme/ThemeCollection.swift
Adds a row of recently picked locations to the Location Picker for quick access.
Within same account | Across accounts (media uploads) | Share Extension
---|----|---
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/iOS/Executions/Version%2012.6/Recent%20locations%20picker.md
Reports:
> [feature/last-picked] Add Recent Locations to location picker

- .github/workflows/generate-sbom.yml
- ownCloud.xcodeproj/project.pbxproj
- sbom.json
Auto-generate SBOM using cdxgen
#1473
> [chore/sbom] Auto-generate SBOM using cdxgen

- ownCloudAppShared/Client/Spaces/SpaceManagementViewController.swift
- SpaceManagementViewController: prevent multiple taps on "Create" or "Save" that could lead to triggering the creation / editing action multiple times
KOKO-1383
> [fix/space-creation-multitaps] Prevent multiple taps on Create/Save Space button

- ownCloud/Client/Viewer/DisplayViewController.swift
- ownCloud/Resources/Localizable.xcstrings
If an item is being deleted while being viewed, the viewer shows a "Item removed" message and - if it is the only file being viewed and the viewer is not the only item in the browser history - "closes" the viewer by removing it from history.
#1484
"Item removed" view | &nbsp;
--|--
> [fix/close-preview-on-delete] "Close" viewer when viewed item is being deleted
