Podfile.lock
ownCloud.xcodeproj/project.pbxproj
ownCloud/Settings/SecuritySettingsSection.swift
ownCloudTests/Security/PasscodeTests.swift

UI tests about integration of passcode feature with settings view.
In progress

Extend UI tests for passcode feature

---

ownCloud/Client/ClientQueryViewController.swift
ownCloud/Server List/ServerListTableViewController.swift

This PR fixes the crash when you try to delete a bookmark on an iPad
https://github.com/owncloud/ios-app/issues/104

Fix for the app crash when bookmark is deleted

---

ownCloud/Bookmarks/BookmarkViewController.swift
ownCloud/Bookmarks/Issues/Issues Subclasses/ConnectionIssueViewController.swift
ownCloud/Client/Actions/NamingViewController.swift
ownCloud/Client/ClientQueryViewController.swift
ownCloud/Resources/en.lproj/Localizable.strings
ownCloud/SDK Extensions/OCItem+Extension.swift
ownCloud/Theming/TVG/TVGImage.swift
ownCloud/Theming/Theme.swift

With this pull request the app is now able to duplicate files and folders.
When you duplicate a folder the naming follows the next schema:
> item-name + _copy_
https://github.com/owncloud/ios-app/issues/23

Duplicate files and folders

---

ownCloud/Bookmarks/BookmarkViewController.swift
ownCloud/SDK Extensions/OCBookmark+Extension.swift
ownCloud/Server List/ServerListTableViewController.swift

- Update to latest SDK
- Code changes required by addition of nullability annotations (untested)

[fix/sdkupdates] Update to latest SDK

---

ownCloud.xcodeproj/project.pbxproj
ownCloud/Client/ClientItemCell.swift
ownCloud/Client/ClientQueryViewController.swift
ownCloud/Resources/Info.plist
ownCloud/Resources/en.lproj/InfoPlist.strings
ownCloud/Resources/en.lproj/Localizable.strings
ownCloud/Resources/es.lproj/InfoPlist.strings
ownCloud/UIKit Extensions/UIImagePickerController+Extension.swift

[feature/uploads] Upload files and pictures from the owncloud app

---

ownCloud/Theming/ThemeCollection.swift

Fixes https://github.com/owncloud/ios-app/issues/159
https://github.com/owncloud/ios-app/issues/159

[fix/progressBar_light_theme] Fix for the status message in Light theme

---

ownCloudTests/Login/EditBookmarkTests.swift
ownCloudTests/UtilsTests.swift

Extend edit bookmark suite (UI test)

---

ownCloud.xcodeproj/project.pbxproj
ownCloud.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
ownCloudTests/Login/DeleteBookmarkTests.swift
ownCloudTests/Login/EditBookmarkTests.swift
ownCloudTests/UtilsTests.swift

To merge after https://github.com/owncloud/ios-app/pull/187

Delete bookmark - UI tests

---

ownCloud/UI Elements/Card Presentation Controller/CardPresentationController.swift

The card menu now returns to the starting position.
https://github.com/owncloud/ios-app/issues/181

The card menu now returns to the starting position.

---

ownCloud/Bookmarks/BookmarkViewController.swift
ownCloud/Client/Actions/Action.swift
ownCloud/Client/Actions/Actions+Extensions/CreateFolderAction.swift
ownCloud/Client/Actions/Actions+Extensions/DeleteAction.swift
ownCloud/Client/Actions/Actions+Extensions/DuplicateAction.swift
ownCloud/Client/Actions/Actions+Extensions/MoveAction.swift
ownCloud/Client/Actions/Actions+Extensions/OpenInAction.swift
ownCloud/Client/Actions/Actions+Extensions/RenameAction.swift
ownCloud/Client/ClientRootViewController.swift

Fixes https://github.com/owncloud/ios-app/issues/188
https://github.com/owncloud/ios-app/issues/188

Fixes the glitches in deleting file by swiping 

---

ownCloud.xcodeproj/project.pbxproj
ownCloud/AppDelegate.swift
ownCloud/Client/Actions/Actions+Extensions/CopyAction.swift
ownCloud/Client/Actions/ClientDirectoryPickerViewController.swift
ownCloud/Client/ClientQueryViewController.swift
ownCloud/Resources/en.lproj/Localizable.strings
ownCloud/Theming/NSObject+ThemeApplication.swift

Now the app is able to copy files and folders to another location.
https://github.com/owncloud/ios-app/issues/122

Copy action

---

ownCloud/Client/ClientQueryViewController.swift
ownCloud/Theming/NSObject+ThemeApplication.swift

Improves some areas of the UX
https://github.com/owncloud/ios-app/issues/192
https://github.com/owncloud/ios-app/issues/198
Made to fix https://github.com/owncloud/ios-app/issues/198 and https://github.com/owncloud/ios-app/issues/192

UX improvements (Color scheme & + button)

---

CONTRIBUTING.md

Added the tx link to contribute on translations on the CONTRIBUTING.md file
https://github.com/owncloud/ios-app/issues/243

Added the tx link to contribute on translations

---

doc/CONFIGURATION.md
ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud.xcscheme
ownCloud/Resources/en.lproj/Localizable.strings
ownCloud/Server List/ServerListTableViewController.swift
ownCloud/Settings/MoreSettingsSection.swift
ownCloud/Settings/SettingsViewController.swift
ownCloud/Tools/VendorServices.swift

PR to fix https://github.com/owncloud/ios-app/issues/247
It adds a new boolean environment variable called `oc:app.is-beta-build`. This should be activated and coded to true when the build is going to be a beta build. 
This new environment variable is used to select messages between different build types.
Also, it adds new mail for feedback and a new link in the _recommend to a friend_ section
https://github.com/owncloud/ios-app/issues/247

Clean up before release

---

ownCloud/Bookmarks/BookmarkViewController.swift
ownCloud/Resources/en.lproj/Localizable.strings
ownCloud/Server List/ServerListTableViewController.swift
ownCloud/Server List/ServerListTableViewController.xib
ownCloudTests/Tools/OwnCloudTests.swift

Fix for https://github.com/owncloud/ios-app/issues/266
https://github.com/owncloud/ios-app/issues/266

Change 'bookmark' with 'account'.

---

ownCloud/Client/ClientRootViewController.swift

This reverts commit f8f601ddc263e8fdcde3ee1b6ebf2084cc90daeb.

Revert "#304 set toolbar translucent to false"

---

ownCloud/Client/ClientQueryViewController.swift

revert #250 implements drag & drop files from outside into the app, because of wrong branch

revert #250 implements drag & drop files from outside into the app

---

ownCloud/Client/Actions/ClientDirectoryPickerViewController.swift
ownCloud/Client/ClientRootViewController.swift
ownCloudTests/Login/CreateBookmarkTests.swift

Remove translucent of toolbar
#304 
All UI elements should match same style

#304 set toolbar translucent to false

---

ownCloud/Client/Actions/NamingViewController.swift

Fixed missing round rect border and clear button
#326 
TextField is better to identify as a text field and easier to use (clear button)
1. Open file list
2. rename file / folder 
or 
2. create folder

Fixed TextField UI 

---

fastlane/Fastfile
fastlane/README.md

Added a fastlane lane to deploy a signed enterprise IPA file after Bitrise tests was successfully.
As a result we have an app version for every build and branch which can be installed on every device.
#343 
Easily install and test branch app version.
Until this branch is merged into the master and until every branch is updated with this fastlane file, it is only testable in this branch and all other Bitrise builds will fail.
1. Go to the Bitrise Dashboard on an iOS device
2. Open Bitrise Build 2471
3. Click on **APPS AND ARTIFACTS**
4. Install `ownCloud.ipa`
5. Open App on device

Generate IPA for Bitrise test builds

---

ownCloud/Gallery/GalleryHostViewController.swift

Fixes an issue where a tapped file finishes downloading, only to be downloaded *again* by the GalleryView, because the latter was using an outdated version of the `OCItem`.

[fix/gallery-view] Fix double-download issue in Gallery View

---

SETUP.md

For compiling the current app code, Xcode 10.2 is required.
Update setup description for interested developers.

Updated new development requirement to Xcode 10.2 in SETUP.md

---

ownCloud.xcodeproj/project.pbxproj
ownCloud/Settings/MoreSettingsSection.swift
ownCloud/Settings/UserInterfaceSettingsSection.swift
ownCloudTests/Security/PasscodeTests.swift
ownCloudTests/SettingsTests.swift

some UI tests to cover the "Settings" section.
Expand UI test coverage

UI tests on "Settings" 

---

docs/antora.yml

This change adds the suffix "(iOS 11+)" to the end of the Antora component label. 
This relates to https://github.com/owncloud/docs/issues/1356.
This is designed to help ensure that it's clear to the user, when browsing the combined documentation, which version of the iOS app docs is which.
By building the combined docs locally and viewing the output.

Update component label with iOS 11+ suffix

---

ownCloud/Bookmarks/BookmarkViewController.swift
ownCloud/Client/ClientRootViewController.swift
ownCloud/SDK Extensions/OCBookmark+Extension.swift
ownCloud/Server List/ServerListTableViewController.swift

Improve handling of 401 Unauthorized responses during OAuth2-authenticated sessions.
#293

[fix/unauthorized] Improve handling of 401 Unauthorized responses

---

fastlane/Fastfile
ownCloud.xcodeproj/project.pbxproj
ownCloud/AppDelegate.swift
ownCloud/Client/Actions/ClientDirectoryPickerViewController.swift
ownCloud/Client/Actions/MoreViewController.swift
ownCloud/Client/Actions/MoreViewHeader.swift
ownCloud/Import/ImportFilesController.swift
ownCloud/Resources/Info.plist
ownCloud/Resources/en.lproj/Localizable.strings
ownCloud/UI Elements/StaticTableViewRow.swift

User can import files using the iOS share sheet. all file types a…
#76 
#443

[feature/share-sheet] Import files from share sheet / Create Folder in Directorypicker

---

ownCloud/Settings/MediaUploadSettingsSection.swift
ownCloudTests/SettingsTests.swift

Polish the Settings suite by adding checks over the latest settings: Display settings, Media upload, and changes in Logging options.

[Earlgrey] Settings' suite expanded

---

external/libzip/libzip.xcodeproj/project.pbxproj
ownCloud File Provider/FileProviderExtension.m
ownCloud File Provider/OCItem+FileProviderItem.m

Revert "[fix/fp-offline-browsing] Allow offline browsing of folders in the File Provider"

---

ownCloud/AppDelegate.swift
ownCloud/SceneDelegate.swift
ownCloud/Settings/Passcode/AppLockManager.swift
ownCloud/Theming/UI/ThemeWindow.swift

- ThemeWindow: add tracking of live ThemeWindows
- AppLockManager: add support for multiple UIWindowScenes
- fixes iOS 13 lock issue
#582
Test plan:
https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.2.1/Passcode%20Lock%20fixes.md

[fix/passcode] Fix iOS 13 passcode screen issue

---

ownCloud/Resources/en.lproj/Localizable.strings
ownCloud/Settings/MoreSettingsSection.swift

- Add Terms Of Use to Settings
- Pointing to GPL license inside the ios-app repo. Please change as necessary. I'm not a lawyer and can't give legal advice.

[feature/tofu] Add Terms Of Use to Settings

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/ios_task_scheduling.adoc

Just changed modification date -> creation date
Added a note explaining that modified assets are not going to be re-uploaded
#647

Update documentation to reflect changes in instant photo upload

---

docs/modules/ROOT/pages/ios_settings.adoc

This PR fixes a build error in the documentation, and relates to https://github.com/owncloud/docs/issues/2522.
Built the docs and the error was no longer present.

Fix docs build errors

---

enterprise/resign/resignOwncloudApp

Signed binaries couldn't be submitted to the app-store. Validation of the IPA failed with AppStore Connect issues ITMS-90046, ITMS-90362.
n/a
See description
- Test app record, bundle Ids, prov. profiles created for App Store submission.
- Re-signed the IPA
- Validated with xcrun altool --validate-app

Fix for the resign script

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/ios_faq.adoc
docs/modules/ROOT/pages/ios_settings.adoc

- FAQ page added
- Remove collapsible menu item
- TOC added to index page to improve usage in mobile browser
```
git clone https://github.com/owncloud/ios-app.git
cd ios-app
git checkout docs/improvements+faq
cd docs
yarn install
yarn antora
yarn serve
```
Test http://localhost:8080/ios-app/

[Docs] Add FAQ and improve navigation

---

.github/ISSUE_TEMPLATE/release_template.md

New line to fill up the XCode version involved in the release process

Add XCode version in release template

---

ownCloud/Client/Sharing/PublicLinkTableViewController.swift
ownCloud/SDK Extensions/OCCore+Extension.swift

[fix/federated-link-share] Bugfix for sharing a received by federated via link

---

fastlane/Fastfile

Fixed path for moved themes repository for fastlane branding script
Fix fastlane branding

[fix/fastlane-themes-repository] Fixed Themes Repository

---

enterprise/resign/README.md
enterprise/resign/resignOwncloudApp
ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift

This issue is mentioned in ticket #894 
#894 
It solves the problem mentioned in #894 
By following the steps mentioned in #894 
- [x ] Bug fix (non-breaking change which fixes an issue)

#894 - Fixed Keyboard does not disappear (on jump to PDF Page)

---

.github/ISSUE_TEMPLATE/release_template.md
.github/pull_request_template.md

This PR updates the internal task for documentation new features and about the release process.
If a feature was changed by a new PR, the developer have to add a new issue with all relevant details to the documentation repository https://github.com/owncloud/docs-client-ios-app/issues.

[github/documentation-tasks] Updated Documentation Tasks

---

ownCloud/Client/Actions/EditDocumentViewController.swift

…) on iOS 16
This PR fixes another crash when opening a PDF in markup mode.

[fix/markup-ios16-crash2] Markup Mode on iOS 16

---

.tx/config

Fix translation sync. https://github.com/owncloud-ci/transifex/pull/52

fix: fix config file for new transifex client

---

SUPPORT.md

org with com replaced

---

README.md

Generated on https://tools.applemediaservices.com/app/1359583808

Fix App Store Badge

---

enterprise/resign/README.md

Clarify Capabilities for App IDs in resign docs

---

CHANGELOG.md

We recently updated the changlog.tmpl file to include a table of contents.
This PR just updates the final CHANGELOG.md file to reflect the changes made.
When merged, we will have all product changelogs in the same format which are also visible on owncloud.com.

[docs-only] Update CHANGELOG.md to include TOC

---

ownCloud/Client/Actions/Actions+Extensions/CollaborateAction.swift

This PR implements #1353.
#1353

[fix/disable-resharing] Disable re-sharing for items in Shares Jail

---

.tx/config

fix: set minimum_perc = 75 in .tx/config

---

.github/workflows/calens.yml

Use Calens GitHub action instead of docker image

[fix/update-calens-github-action] Calens GitHub Action: Replace docker with native action

---

ownCloud.xcodeproj/project.pbxproj

New version number 12.3.1 for fixing vanilla app branding assets, which was build locally and had the wrong (uncleaned) branding assets in the build folder.

[fix/release-12.3.1] Version 12.3.1 - Fix Vanilla Branding Assets

---

.github/workflows/build-and-analyze.yml

Simplify and stabilize ci using https://github.com/marketplace/actions/mxcl-xcodebuild
- :robot:

ci: use mxcl/xcodebuild

---

.github/workflows/pull-transifex.yml
tools/normalizestrings/main.swift

- normalizestrings: add xcstrings normalization support
- pull-transifex.yml: add normalizestrings xcstrings normalization
Goal: improve development experience with xcstrings files

[fix/xcstrings-format] xcstrings normalization to Xcode style

---

.github/workflows/push-transifex.yml

fix: remove --skip from tx push

---

ownCloudAppShared/Client/Collection Views/Supplementary Cells/TitleSupplementaryCell.swift

- TitleSupplementaryCell: fix "The visually clearly recognizable headings "Pending", "Accepted" and "Rejected" are not marked as such." from #1331
#1331

[fix/a11y-1331] Add `header` trait to collection view section header

---

ownCloud/Client/Actions/EditDocumentViewController.swift

- EditDocumentViewController: add code path for iOS 26+ to enable the editing mode
Note for QA: may need to be tested on a real device running iOS 26. In my testing, enabling markup mode also worked in the Simulator, but there drawing was not possible.
#1498

[fix/enable-markup-ios26] Auto-enable markup on iOS 26
